using System.Collections.Generic;

namespace Achievements
{
	internal class AndroidAchievements
	{
		public static Dictionary<AchievementType, string> achievementIds = new Dictionary<AchievementType, string>
		{
			{
				AchievementType.Queen,
				"CgkIyurnu4kPEAIQRw"
			},
			{
				AchievementType.Princess,
				"CgkIyurnu4kPEAIQSA"
			},
			{
				AchievementType.Duchess,
				"CgkIyurnu4kPEAIQSQ"
			},
			{
				AchievementType.Marchioness,
				"CgkIyurnu4kPEAIQSg"
			},
			{
				AchievementType.Countess,
				"CgkIyurnu4kPEAIQSw"
			},
			{
				AchievementType.Viscountess,
				"CgkIyurnu4kPEAIQTA"
			},
			{
				AchievementType.Baroness,
				"CgkIyurnu4kPEAIQTQ"
			},
			{
				AchievementType.Dame,
				"CgkIyurnu4kPEAIQTg"
			},
			{
				AchievementType.BestScore120000,
				"CgkIyurnu4kPEAIQTw"
			},
			{
				AchievementType.BestScore90000,
				"CgkIyurnu4kPEAIQUA"
			},
			{
				AchievementType.BestScore60000,
				"CgkIyurnu4kPEAIQUQ"
			},
			{
				AchievementType.BestScore30000,
				"CgkIyurnu4kPEAIQUg"
			},
			{
				AchievementType.BestScore24000,
				"CgkIyurnu4kPEAIQUw"
			},
			{
				AchievementType.BestScore18000,
				"CgkIyurnu4kPEAIQVA"
			},
			{
				AchievementType.BestScore12000,
				"CgkIyurnu4kPEAIQVQ"
			},
			{
				AchievementType.BestScore6000,
				"CgkIyurnu4kPEAIQVg"
			},
			{
				AchievementType.BestScore1000,
				"CgkIyurnu4kPEAIQVw"
			},
			{
				AchievementType.HappilyEverAfter,
				"CgkIyurnu4kPEAIQWA"
			},
			{
				AchievementType.NoOneLeftBehind,
				"CgkIyurnu4kPEAIQWQ"
			},
			{
				AchievementType.ChickenRun,
				"CgkIyurnu4kPEAIQWg"
			}
		};
	}
}
